default_platform(:ios)

platform :ios do
  lane :fetch_profile do
    app_store_connect_api_key(
      key_id: "XHA9VM622Z",
      issuer_id: "317cf7b1-ad60-408e-b78a-42a1bd395b0b",
      key_filepath: File.expand_path("~/.private_keys/AuthKey_XHA9VM622Z.p8"),
      in_house: false
    )

    sigh(
      app_identifier: "com.photomate.app",
      development: true,
      force: true
    )
  end

  lane :submit do
    api_key = app_store_connect_api_key(
      key_id: "XHA9VM622Z",
      issuer_id: "317cf7b1-ad60-408e-b78a-42a1bd395b0b",
      key_filepath: File.expand_path("~/.private_keys/AuthKey_XHA9VM622Z.p8")
    )

    deliver(
      submit_for_review: true,
      app_identifier: "com.photomate.app",
      app_version: "1.0.1",
      build_number: "4",
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      run_precheck_before_submit: false,
      api_key: api_key
    )
  end
end
